### ISSUE TITLE
error thrown when calling -signin function

### ISSUE THREAD

**Issue by Leon16** [craigaps/RelyingPartyKit#1]
I had managed to register the user with the Passkey. Now I am at the stage of calling -signin API of RelyingPartyKit API. The problem happens at the point in the 

`func authorizationController(controller: ASAuthorizationController, didCompleteWithAuthorization authorization: ASAuthorization) delegate`

I got the credentialAssertion and use it to call 

`let token = try await rpClient.signin(signature: credentialAssertion.signature, clientDataJSON: credentialAssertion.rawClientDataJSON, authenticatorData: credentialAssertion.rawAuthenticatorData, credentialId: credentialAssertion.credentialID)
`
I got the throw error here. I went into RelyingPartyKit and check the following API in Client module:

`public func signin(signature: Data, clientDataJSON: Data, authenticatorData: Data, credentialId: Data) async throws -> Token 
`
I checked the content of the verification content as the following:

```
(lldb) p verification
(RelyingPartyKit.FIDO2Verification) $R0 = {
  clientDataJSON = "eyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoiRm5ONVBQakJKOTNKUFJva1hxSGdGWDdGTVo1dGRqbUFXWXkybWZVMFY0ayIsIm9yaWdpbiI6Imh0dHBzOi8vcnBzLWFwcC52eHdubWJ3bXUyNC5hdS1zeWQuY29kZWVuZ2luZS5hcHBkb21haW4uY2xvdWQifQ"
  authenticatorData = "OOlzESxt-hUx2TsAr4zJn-EMZkO9p96cH0JASwBVO2kdAAAAAA"
  credentialId = "YLGj_srqWCINGiW-JVe5Trbmf2c"
  signature = "MEYCIQDsr2T286y2ZGyX2OZLUCPMjSgkowprCPUYtCnp5gfjqAIhAJyQzSnD-aMl1ZeHfxKbkk4HE3iQ4tNvoSlmfdeVpqFF"
}

```
Calling ` let (data, response) = try await URLSession.shared.upload(for: request, from: body)` gave the error in response. I used the above data in Postman to call the /v1/signin/ directly and get the error:

```
{
    "error": true,
    "reason": "userHandle is required"
}
```

Comparing the example data you set in the Postman import file it does added the “userHandle” but your 
struct FIDO2Verification: Encodable  definition it is not defined. In WebAuthn guide this property is optional. 

Could you help check and advise whether this is the cause of the error thrown or how we should get this around?

**Comment by craigaps** [comment]
Hey @Leon16, you might want to update the RelyingPartyKit SPM in your sample app.  I added a parameter to the `signin` function to include `userId` (`userHandle` in the Postman script) which is documented in the README.  Simply provide the `userID` from the `ASAuthorizationPlatformPublicKeyCredentialAssertion` parameter.

**Verifying an account with Passkey**
https://github.com/craigaps/RelyingPartyKit#verifying-an-account-with-passkey

**Comment by craigaps** [comment]
@Leon16 thanks for the feedback.  The README has been updated to reflect your suggestions.
